# Generated by Django 4.1 on 2023-12-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tags', models.CharField(choices=[('塩', '塩'), ('醤油', '醤油'), ('豚骨', '豚骨'), ('味噌', '味噌'), ('魚介', '魚介'), ('混ぜそば', '混ぜそば'), ('つけ麺', 'つけ麺')], max_length=20)),
            ],
        ),
    ]
